DTO_TYPE = "func"
name = "f"

[globals]
DTO_TYPE = "dict"
c = 42

[globals.math]
DTO_TYPE = "module"
name = "math"
fields = {}

[code]
DTO_TYPE = "code"

[code.fields]
DTO_TYPE = "dict"
co_argcount = 1
co_cellvars = []
co_code = "64017d017400a0017c007c01140074021400a1015300"
co_filename = "/home/dkefir03/labs/ISP-2022-053504/main.py"
co_firstlineno = 71
co_flags = 67
co_freevars = []
co_kwonlyargcount = 0
co_lnotab = "00010401"
co_name = "f"
co_nlocals = 2
co_posonlyargcount = 0
co_stacksize = 4

[code.fields.co_consts]
DTO_TYPE = "list"
__dto__list_dict_item0 = {}
__dto__list_dict_item1 = 123

[code.fields.co_names]
DTO_TYPE = "list"
__dto__list_dict_item0 = "math"
__dto__list_dict_item1 = "sin"
__dto__list_dict_item2 = "c"

[code.fields.co_varnames]
DTO_TYPE = "list"
__dto__list_dict_item0 = "x"
__dto__list_dict_item1 = "a"

